export const initialState = {
  noteModal: {
    id: null,
    title: '',
    text: '',
    creator: '',
    body: '',
    date: '',
    colorPriority: '',
  },
  modalVisible: false,
  notes: [
    {
      id: 1,
      title: 'My card #1',
      text: 'Text long for debug project, ok leave #1',
      body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fuga omnis labore ab perspiciatis ad, asperiores debitis atque unde porro provident sapiente, dolorem dolores libero ducimus optio! Laborum suscipit aspernatur id quae quod libero vero dolor aut odio incidunt, tenetur culpa sequi recusandae molestiae, ipsum fugit nam porro. Iusto, eos?',
      creator: 'JF',
      date: '14/04/2023',
      colorPriority: 'blue',
    },
    {
      id: 2,
      title: 'My card #2',
      text: 'Text long for debug project, ok leave #2',
      body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fuga omnis labore ab perspiciatis ad, asperiores debitis atque unde porro provident sapiente, dolorem dolores libero ducimus optio! Laborum suscipit aspernatur id quae quod libero vero dolor aut odio incidunt, tenetur culpa sequi recusandae molestiae, ipsum fugit nam porro. Iusto, eos?',
      creator: 'JF',
      date: '12/04/2023',
      colorPriority: 'black',
    },
    {
      id: 3,
      title: 'My card #3',
      text: 'Text long for debug project, ok leave #3',
      body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate fuga omnis labore ab perspiciatis ad, asperiores debitis atque unde porro provident sapiente, dolorem dolores libero ducimus optio! Laborum suscipit aspernatur id quae quod libero vero dolor aut odio incidunt, tenetur culpa sequi recusandae molestiae, ipsum fugit nam porro. Iusto, eos?',
      creator: 'JF',
      date: '13/04/2023',
      colorPriority: 'red',
    },
  ],
}
